package com.ghost.tagger.data.enums

import kotlinx.serialization.Serializable

@Serializable
enum class TagSource {
    MANUAL, // Added by User
    AI,     // Generated by your ML model
    FILE ;// Read from existing file metadata

    fun priority(): Int{
        return when (this){
            MANUAL -> 3
            AI -> 2
            FILE -> 1
        }
    }
}